name: philiprehberger_result_type
description: Rust-style Result type for type-safe error handling with pattern matching
version: 0.2.0
homepage: https://philiprehberger.com/open-source-packages/dart/philiprehberger_result_type
repository: https://github.com/philiprehberger/dart-result-type
issue_tracker: https://github.com/philiprehberger/dart-result-type/issues

environment:
  sdk: ^3.6.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
